rabbitmq/rabbitmq-management-agent

- src/rabbit_mgmt_db_handler.erl
Part of https://github.com/rabbitmq/rabbitmq-management/issues/41
> Send events to new management collectors

- src/rabbitmq_management_agent.app.src
Related to https://github.com/rabbitmq/rabbitmq-server/pull/776
Part of https://github.com/rabbitmq/rabbitmq-server/issues/735
> Stub for broker_version_requirements

- src/rabbit_mgmt_external_stats.erl
Part of https://github.com/rabbitmq/rabbitmq-management/pull/229
https://github.com/rabbitmq/rabbitmq-management/issues/208
> Report GC and context switches stats in node_stats

- src/Elixir.RabbitMQ.CLI.Ctl.Commands.ResetStatsDbCommand.erl
- src/rabbit_mgmt_storage.erl
Closes https://github.com/rabbitmq/rabbitmq-management/issues/295
> CLI command to reset stats DB

- src/rabbit_mgmt_metrics_collector.erl
- src/rabbit_mgmt_storage.erl
> Reset old_aggr_stats

- src/rabbit_mgmt_metrics_collector.erl
Fixes: https://github.com/rabbitmq/rabbitmq-management/issues/350
> Fix typo that caused missing exchange out rates

- src/rabbit_mgmt_gc.erl
Part of https://github.com/rabbitmq/rabbitmq-server/issues/1125
> Check process aliveness on remote nodes

- src/rabbit_mgmt_format.erl
> Format consumer arguments in clean_consumer_details/1

- src/rabbit_mgmt_format.erl
Part of https://github.com/rabbitmq/rabbitmq-management/issues/393.
> Format ssl_opts in HTTP API listeners and Web contexts

- src/rabbit_mgmt_format.erl
Part of https://github.com/rabbitmq/rabbitmq-management/issues/421
> Let already formatted AMQP tables pass through

- src/rabbit_mgmt_metrics_collector.erl
`dict` operations on the metrics collector seem to be taken a large amount of time, as profiled with looking glass. See cachegrind output:
Before:
After:
> Performance enhancement: replace dict by maps

- src/rabbit_mgmt_data.erl
This allows the data to be merged correctly further down.
Requires: https://github.com/rabbitmq/rabbitmq-management/issues/525
Part of: https://github.com/rabbitmq/rabbitmq-management/issues/525
[#153738257]
> Only return metrics_gc_queue_length metrics for the requested node.

- src/rabbit_mgmt_external_stats.erl
> Make warning a bit more verbose

- include/rabbit_mgmt_metrics.hrl
- src/rabbit_mgmt_data.erl
- src/rabbit_mgmt_metrics_collector.erl
Rate stats for monitoring of high connection churn scenarios
Part of https://github.com/rabbitmq/rabbitmq-server/issues/1723
> Report connection/channel/queue churn

- src/rabbit_mgmt_db_handler.erl
- src/rabbit_mgmt_external_stats.erl
- src/rabbit_mgmt_format.erl
Depends on: https://github.com/rabbitmq/rabbitmq-server/pull/1706
> Quorum queues

- src/rabbit_mgmt_format.erl
> Serialise decimal arguments

- src/rabbit_mgmt_format.erl
- src/rabbit_mgmt_metrics_collector.erl
[#163089472]
References rabbitmq/rabbitmq-management#649
> Integrate single active consumer

- src/exometer_slide.erl
- src/rabbit_mgmt_data.erl
- src/rabbit_mgmt_data_compat.erl
- src/rabbit_mgmt_ff.erl
- src/rabbit_mgmt_format.erl
See rabbitmq/rabbitmq-server#1818 for a description of this change.
> Feature flags support + make #amqqueue{} private

- include/rabbit_mgmt_metrics.hrl
- src/exometer_slide.erl
- src/rabbit_mgmt_data.erl
- src/rabbit_mgmt_data_compat.erl
- src/rabbit_mgmt_ff.erl
- src/rabbit_mgmt_metrics_collector.erl
Part of rabbitmq/rabbitmq-server#1904.
[#165548314]
> New channel metric: dropped unroutable messages

- src/rabbit_mgmt_external_stats.erl
While at it, log exceptions every time and as errors.
Closes #86.
> Be extra defensive when inferring how many file descriptors are used

- src/rabbit_mgmt_format.erl
References rabbitmq/rabbitmq-common#339.
Part of rabbitmq/rabbitmq-management#749.
> Forward functions extracted into rabbit_misc

- src/rabbit_mgmt_format.erl
Required by https://github.com/rabbitmq/rabbitmq-management/pull/753
> Format queue info proplist

- src/rabbit_mgmt_external_stats.erl
This allows logging errors only once every 10 minutes. Prior to an
earlier change this time was stored in the process dictionary. Storing
in the state is the "correct" way to do it.
Follow-up to #90
> Store last error log time in state

- src/rabbit_mgmt_format.erl
Part of: https://github.com/rabbitmq/rabbitmq-server/pull/2380
**This work has be carried out by** [Erlang Solutions](https://www.erlang-solutions.com/) **and sponsored by** [CloudAMQP](https://www.cloudamqp.com/)
> Acquire internal_user record fileds via new API(s)
