src/rabbit_mgmt_db_handler.erl
As well as `rabbitmq_management`, of course.
Some have rabbitmq_management disabled, which means its .app file is
not loaded.
Fixes https://github.com/rabbitmq/rabbitmq-management/issues/33.
=> Support configuring mgmt agent via rabbitmq_management_agent

src/rabbit_mgmt_external_stats.erl
Keys `log_file` and `sasl_log_file` are replaced by a single key `log_files` which returns a list.
References rabbitmq/rabbitmq-server#94.
=> Use the new rabbit:log_locations/0 API

src/rabbit_mgmt_external_stats.erl
As part of https://github.com/rabbitmq/rabbitmq-server/issues/557, data must be sent raw to the event collector in order to properly calculate the average operation times and instant values.
=> Avoid average operation time calculations in the agent

src/rabbit_mgmt_db_handler.erl
Part of https://github.com/rabbitmq/rabbitmq-management/issues/173
=> Send channel and queue stats to their own collectors to avoid race conditions

src/rabbit_mgmt_storage.erl, test/metrics_SUITE.erl
The overview reported negative message counters after reset the stats, as the reset never succeed.
Fixes https://github.com/rabbitmq/rabbitmq-management-agent/pull/23 as part of #22
=> Fix typo and add tests to verify that stats recover after reset

src/rabbit_mgmt_agent_sup.erl, src/rabbit_mgmt_external_stats.erl, src/rabbit_mgmt_gc.erl, src/rabbit_mgmt_metrics_collector.erl, test/rabbit_mgmt_gc_SUITE.erl
Part of https://github.com/rabbitmq/rabbitmq-management-agent/issues/25
=> Periodic garbage collection of stats

src/exometer_slide.erl, src/rabbit_mgmt_format.erl, src/rabbit_mgmt_gc.erl, src/rabbit_mgmt_metrics_collector.erl, src/rabbit_mgmt_metrics_gc.erl, src/rabbit_mgmt_storage.erl, test/exometer_slide_SUITE.erl
Fixes: https://github.com/rabbitmq/rabbitmq-management/issues/353
Includes:
* dialyzer fixes
* Fix for a scenario where the first sample in a slide gets delayed and merged with the next.
* Normalization fix for `exometer_slide:last_two`
=> Core metrics deletion markers

.gitignore, src/rabbit_mgmt_metrics_collector.erl
returning a set of ets operations.
This avoids inserting into the same exometer slide data structure
multiple times each collection and thus reduces the amount of
unrealised rate data is kept around until the next interval.
Fixes: https://github.com/rabbitmq/rabbitmq-management/issues/354
=> Make aggregate_entry a pure function 

src/rabbit_mgmt_gc.erl, test/rabbit_mgmt_gc_SUITE.erl
It leaked `consumer_stats` when the queue still existed, now both entity and process must exist to keep the stats.
Part of https://github.com/rabbitmq/rabbitmq-management-agent/issues/32
=> Test and clean up stats dependent on both process and entity

src/rabbit_mgmt_format.erl
Fixes JSON serialisation e.g. when a TCP listener has
a single atom property such as "binary" configured.
Fixes #34.
=> Convert single atom options to {Option, true}

src/rabbit_mgmt_format.erl
Some are functions, others contain deeply nested data structures that
nobody cares about in GET /api/overview output. It is easier to filter
them out than to find a way to convert them into something that
can serialise.
Fixes #36.
=> Filter out socket options that cannot be sensibly serialised to JSON

src/rabbit_mgmt_format.erl
Fixes rabbitmq/rabbitmq-management#364, references #36.
=> Filter out cipher suites as well

src/rabbit_mgmt_agent_config.erl, src/rabbit_mgmt_metrics_collector.erl
Node startup must fail if retention policies are missing, which from
3.6.7 are also required for collection. Instead of crash with a
function_clause, collectors now return a clear message.
Part of https://github.com/rabbitmq/rabbitmq-management-agent/issues/41
[#143308479]
=> Throw an error if retention policies are missing

src/rabbit_mgmt_metrics_collector.erl
node_coarse_stats might ocassionally generate atoms, i.e. when disk
monitoring is not available, which should be filtered out.
Part of https://github.com/rabbitmq/rabbitmq-management/issues/375
=> Ensure numeric defaults, so atoms are not passed through

src/rabbit_mgmt_format.erl
Part of fix for rabbitmq/rabbitmq-server#1243
`term_to_binary` can change in different OTP versions, `phash2` should be safe.
Args hash is used in management API to identify bindings.
It should be safe to change the algorithm, because it's not a persistent value.
=> Replace term_to_binary with phash2 for args hash.

src/rabbit_mgmt_external_stats.erl
re rabbitmq/rabbitmq-server#1259
=> Use total system process rss memory when reporting vm memory

src/rabbit_mgmt_external_stats.erl, src/rabbit_mgmt_metrics_collector.erl
Fixes rabbitmq/rabbitmq-management#427
Depends on rabbitmq/rabbitmq-server#1278
=> Only preserve stats for local queues

src/rabbit_mgmt_format.erl, src/rabbit_mgmt_metrics_collector.erl
Some formatting operations, as utf8 conversions on connection stats, are very expensive. The collector reads and updates metrics on every collection interval, however some metrics such as connection creation never change. This patch checks if the `created` metrics already exist on the stats table and if that's the case, it does nothing.
Before:
After:
The second commit avoids traversing the full list of `channel_stats` when only the first element (`idle_since`) needs to be formatted.
=> Performance optimisations

src/rabbit_mgmt_format.erl
jsx expects a proplist key to be an Erlang binary, an integer or an atom. It doesn't accept an Erlang string, probably because it's difficult to distinguish from a list of integers.
This patch first tried to format `sni_hosts` but it turns out to be trickier since this is a case of recursive options. Since SNI options are not displayed in any way in the UI and supported by HTTP API clients,
we can solve the problem by simply skipping them as we already do for a few other options.
Fixes rabbitmq/rabbitmq-management#567.
=> rabbit_mgmt_format: Convert `sni_hosts` to something compatible with jsx

src/rabbit_mgmt_db_handler.erl
=> Force events refresh when the management plugin is enabled

src/rabbit_mgmt_data.erl
Not the local one, all HTTP requests to /api/nodes/<node> were reporting stats for the node running the management plugin instead of the requested one.  Fixes the enhancement in  https://github.com/rabbitmq/rabbitmq-server/issues/1723
=> Request churn rates for the given node

src/rabbit_mgmt_format.erl
If a queue is bainf deleted and it takes some time, for example if there
are many bindings, the management UI crashes formatting the status.
Split the status and terminated_by name into proplist so json fomatter
does not crash.
How to reproduce:
- declare a queue
- add 20000 bindings
- keep the queues page tab open
- delete the queue
- see 500 error on the queues page and error message in the log
=> Format {terminated_by, Name} status for queues.

priv/schema/rabbitmq_management_agent.schema, src/rabbit_mgmt_agent_sup.erl
Allows external stats to be gathered for the prometheus plugin, while
removing all metrics collection/aggregation and unnecesary management
services.
To disable set app env `disable_metrics_collector` to `true`.
Defaults `false`
[#164376052]
=> Option to disable metrics collector on startup

src/rabbit_mgmt_db_handler.erl
This call is still necessary as @dcorbacho explained in #58
=> Restore event refresh call

src/rabbit_mgmt_format.erl
Noticed when working on the management-only changes, but the type was missing since the quorum queue work was done - and types introduced!
=> Include the queue type in queue formatting

src/rabbit_mgmt_format.erl
To reproduce:
* Declare a durable queue that is matched by no policies [in the default vhost]
* Run `curl -u guest:guest -X GET http://127.0.0.1:15672/api/queues/%2F | jq` and inspect the value of the `effective_policy_definition` field
Closes rabbitmq/rabbitmq-management#701.
References rabbitmq/rabbitmq-management#74, rabbitmq/rabbitmq-management#424.
=> Format blank effective policy definitions as a JSON object

src/rabbit_mgmt_format.erl
So that it uses the same short name as the x-queue-type argument uses.
=> Format queue type field

src/exometer_slide.erl
There is only a single point in the code we need the ordering at which
point we can explicitly sort the result.
A quick test running `exometer_slide:sum/1` on 5 slides with 2000 samples each brought the time taken down from ~16000 microseconds to ~2000 microseconds.
=> Replace use of orddict with map
